language: node_js
node_js:
  - "14.16.0"
before_script:
  - npm install -g @angular/cli
  - npm install
  - cd studybuddies
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
install:
  - npm install codacy-coverage --save
script:
  - npm update
  - npm run build
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --code-coverage
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/studybuddies/lcov.info
  #
  
  
  

