language: node_js
node_js:
  - "14.16.0"
before_script:
  - npm install -g @angular/cli
  - cd studybuddies
install:
  - pip install codacy-coverage
script:
  - npm run test-headless
  - ng build --prod --base-href https://github.com/sanmargom2/Studybuddies_Frontend.git
